(() => {
  'use strict';
  const KEY = 'becoming_workspace_private_v1';
  const VERSION = 1;
  const $ = id => document.getElementById(id);
  const uid = () => `${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const today = () => new Date().toISOString().slice(0,10);
  const blank = () => ({version:VERSION,collections:{tasks:[],projects:[],courses:[],study:[],reading:[],english:[],health:[],sop:[],inventory:[],recipes:[],journal:[],travel:[],style:[],money:[],reviews:[],achievements:[]}});
  function load(){try{const data=JSON.parse(localStorage.getItem(KEY)||'null');return data?.collections?data:blank()}catch{return blank()}}
  let state=load(),route='home',editing=null;
  function save(){localStorage.setItem(KEY,JSON.stringify(state));toast('已保存在此浏览器 · Saved locally')}
  function toast(text){const el=$('toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1800)}
  const groups=[
    ['NOW',[['home','⌂','首页 Home'],['plan','◷','今日计划 Plan']]],
    ['WORK',[['work','□','工作 Work'],['university','U','大学 University']]],
    ['LEARN',[['study','K','学习 Study'],['reading','R','阅读 Reading']]],
    ['WELLBEING',[['health','＋','健康 Health'],['life','L','生活 Life']]],
    ['REFLECT',[['review','↺','复盘 Review'],['data','⋯','数据 Data']]]
  ];
  const specs={
    tasks:{title:'任务 · Task',fields:[['title','标题 · Title','text'],['status','状态 · Status','select',['next','doing','waiting','done']],['date','日期 · Date','date'],['area','领域 · Area','text'],['notes','下一步 / 备注 · Notes','textarea']]},
    projects:{title:'项目 · Project',fields:[['title','项目 · Project','text'],['status','状态 · Status','select',['planning','active','paused','complete']],['date','截止 · Deadline','date'],['area','领域 · Area','text'],['notes','成果 / 下一步 · Outcome','textarea']]},
    courses:{title:'课程 · Course',fields:[['title','课程 · Course','text'],['status','状态 · Status','select',['active','review','complete']],['date','下一截止 · Next deadline','date'],['area','学期 / 类别 · Term','text'],['notes','Reading / Assessment / Notes','textarea']]},
    study:{title:'学习领域 · Study area',fields:[['title','领域 · Area','text'],['status','水平 · Level','select',['L1','L2','L3']],['date','复习日期 · Review date','date'],['area','频率 · Cadence','text'],['notes','资源 / 毕业测试 · Resources','textarea']]},
    reading:{title:'阅读 · Reading',fields:[['title','书 / 论文 / 电影 · Title','text'],['status','状态 · Status','select',['to read','reading','finished','paused']],['date','日期 · Date','date'],['area','类型 · Type','text'],['notes','观点 / 引用 / 输出 · Notes','textarea']]},
    english:{title:'英语练习 · English',fields:[['title','练习内容 · Session','text'],['status','类型 · Type','select',['listening','speaking','reading','writing','vocabulary']],['date','日期 · Date','date'],['area','时长 · Minutes','number'],['notes','错误与改进 · Reflection','textarea']]},
    health:{title:'健康记录 · Health',fields:[['title','记录 · Entry','text'],['status','类型 · Type','select',['sleep','exercise','food','skincare','mood','other']],['date','日期 · Date','date'],['area','数值 / 时长 · Value','text'],['notes','备注 · Notes','textarea']]},
    sop:{title:'生活 SOP',fields:[['title','步骤 / Routine','text'],['status','频率 · Cadence','select',['daily','weekly','monthly','seasonal']],['date','下次日期 · Next date','date'],['area','时段 · Time','text'],['notes','步骤 · Steps','textarea']]},
    inventory:{title:'库存 · Inventory',fields:[['title','物品 · Item','text'],['status','位置 · Location','select',['room','bathroom','kitchen','fridge','bag','other']],['date','到期 / 补货日 · Date','date'],['area','数量 · Quantity','number'],['notes','补货线 / 备注 · Notes','textarea']]},
    recipes:{title:'菜谱 · Recipe',fields:[['title','菜名 · Recipe','text'],['status','菜系 · Cuisine','text'],['date','上次制作 · Last made','date'],['area','难度 / 时间 · Level','text'],['notes','食材与步骤 · Ingredients & steps','textarea']]},
    journal:{title:'日记 · Journal',fields:[['title','标题 · Title','text'],['status','心情 · Mood','text'],['date','日期 · Date','date'],['area','标签 · Tags','text'],['notes','正文 · Entry','textarea']]},
    travel:{title:'旅行 · Travel',fields:[['title','地点 · Place','text'],['status','状态 · Status','select',['wishlist','planned','visited']],['date','日期 · Date','date'],['area','国家 / 地区 · Region','text'],['notes','路线 / 记忆 · Notes','textarea']]},
    style:{title:'风格 · Style',fields:[['title','造型 / 灵感 · Look','text'],['status','类别 · Type','select',['outfit','makeup','hair','inspiration']],['date','日期 · Date','date'],['area','场合 / 色彩 · Occasion','text'],['notes','单品 / 观察 · Notes','textarea']]},
    money:{title:'金钱 · Money',fields:[['title','项目 · Item','text'],['status','类型 · Type','select',['expense','income','budget','wishlist']],['date','日期 · Date','date'],['area','金额 · Amount','number'],['notes','币种 / 备注 · Notes','textarea']]},
    reviews:{title:'复盘 · Review',fields:[['title','周期 · Review','text'],['status','能量 · Energy','select',['low','medium','high']],['date','日期 · Date','date'],['area','主题 · Theme','text'],['notes','产出 / 阻碍 / 下一步 · Reflection','textarea']]},
    achievements:{title:'成就 · Achievement',fields:[['title','成就 · Achievement','text'],['status','等级 · Level','select',['start','progress','stable']],['date','日期 · Date','date'],['area','领域 · Area','text'],['notes','证据 · Evidence','textarea']]}
  };
  function rows(key){return state.collections[key]||[]}
  function nav(){ $('nav').innerHTML=groups.map(([g,items])=>`<div class="nav-group">${g}</div>${items.map(([id,icon,label])=>`<button class="nav-button ${route===id?'active':''}" data-route="${id}"><span class="nav-icon">${icon}</span>${label}</button>`).join('')}`).join('');document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>go(b.dataset.route))}
  function go(next){route=next;nav();render();$('sidebar').classList.remove('open');$('main').focus();history.replaceState(null,'',`#${next}`)}
  const pageHead=(eyebrow,title,desc,action='')=>`<header class="page-head"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${desc}</p></div>${action?`<div class="page-actions">${action}</div>`:''}</header>`;
  const empty=(key,label)=>`<div class="empty">还没有记录。<button class="ghost" data-add="${key}">＋ 添加 ${label}</button></div>`;
  function list(key,limit=50){const data=rows(key).slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,limit);if(!data.length)return empty(key,specs[key].title.split('·')[0]);return `<div class="list">${data.map(x=>`<div class="row"><button class="row-main" data-edit="${key}:${x.id}"><strong>${esc(x.title||'Untitled')}</strong><small>${esc([x.date,x.area,x.notes].filter(Boolean).join(' · '))}</small></button><span class="pill">${esc(x.status||'record')}</span></div>`).join('')}</div>`}
  function collectionPage(title,english,desc,tabs){let active=tabs[0][0];const hash=location.hash.split('/')[1];if(tabs.some(x=>x[0]===hash))active=hash;const tab=tabs.find(x=>x[0]===active);$('breadcrumbs').textContent=`${title} · ${english}`;$('main').innerHTML=pageHead(english.toUpperCase(),`${title} · ${english}`,desc,`<button class="primary" data-add="${tab[1]}">＋ 新建 New</button>`)+`<div class="tabs">${tabs.map(([id,,label])=>`<button class="${id===active?'active':''}" data-subtab="${id}">${label}</button>`).join('')}</div><section class="card full"><div class="section-head"><div><h2>${tab[2]}</h2><p>${rows(tab[1]).length} records · 全部可编辑</p></div></div>${list(tab[1])}</section>`;document.querySelectorAll('[data-subtab]').forEach(b=>b.onclick=()=>{location.hash=`${route}/${b.dataset.subtab}`;render()});bindDynamic()}
  function home(){const open=rows('tasks').filter(x=>x.status!=='done').slice(0,3),due=rows('tasks').filter(x=>x.date===today()).length;$('breadcrumbs').textContent='首页 · Home';$('main').innerHTML=pageHead('PRIVATE PERSONAL OS','今天 · Today','先看真正需要推进的事；所有记录只保存在当前浏览器。',`<button class="ghost" data-route-jump="plan">打开计划 Open plan</button>`)+`<div class="grid"><section class="card metric"><span>开放任务 · Open tasks</span><strong>${rows('tasks').filter(x=>x.status!=='done').length}</strong></section><section class="card metric"><span>今日到期 · Due today</span><strong>${due}</strong></section><section class="card metric"><span>本地记录 · Local records</span><strong>${Object.values(state.collections).reduce((n,a)=>n+a.length,0)}</strong></section><section class="card wide"><div class="section-head"><div><h2>三件要事 · Top Three</h2><p>保持短，才能真正开始。</p></div><button class="ghost" data-add="tasks">＋ Task</button></div>${open.length?`<div class="list">${open.map(x=>`<div class="row"><button class="row-main" data-edit="tasks:${x.id}"><strong>${esc(x.title)}</strong><small>${esc(x.date||'No date')}</small></button><span class="pill">${esc(x.status)}</span></div>`).join('')}</div>`:empty('tasks','任务')}</section><aside class="card"><h2>快速进入 · Quick Access</h2><p>每次只打开需要的模块。</p><div class="quick-grid">${[['work','工作','Work'],['study','学习','Study'],['health','健康','Health'],['life','生活','Life'],['review','复盘','Review'],['data','数据','Data']].map(x=>`<button class="quick" data-route-jump="${x[0]}"><strong>${x[1]}</strong><small>${x[2]}</small></button>`).join('')}</div></aside><section class="card full"><div class="notice"><strong>隐私模式：</strong>本站没有账号、数据库、分析代码或外部请求。换设备前请在“数据”页面导出 JSON。</div></section></div>`;bindDynamic()}
  function dataPage(){$('breadcrumbs').textContent='数据 · Data';const total=Object.values(state.collections).reduce((n,a)=>n+a.length,0);$('main').innerHTML=pageHead('LOCAL DATA','数据 · Data','备份、迁移或清空当前浏览器里的私人记录。')+`<div class="grid"><section class="card metric"><span>本地记录 · Records</span><strong>${total}</strong></section><section class="card wide"><h2>备份与迁移 · Backup</h2><p>JSON 文件只下载到你的电脑，不上传网站。</p><div class="page-actions"><button class="primary" id="exportData">下载 JSON · Export</button><button class="ghost" id="importData">导入 JSON · Import</button><button class="danger" id="clearData">清空全部 · Clear</button></div></section><section class="card full"><h2>隐私说明 · Privacy</h2><p>程序使用浏览器 localStorage。仓库只包含通用程序，不包含你填写的记录；本站也不会连接分析、广告或云端数据库。</p></section></div>`;$('exportData').onclick=exportData;$('importData').onclick=()=>$('importInput').click();$('clearData').onclick=()=>{if(confirm('确定清空当前浏览器的全部记录吗？请先导出备份。')){state=blank();save();render()}}}
  function render(){const routes={home,plan:()=>collectionPage('计划','Plan','任务、日期和下一步。',[['tasks','tasks','任务 · Tasks'],['projects','projects','项目 · Projects']]),work:()=>collectionPage('工作','Work','项目与执行动作分开管理。',[['projects','projects','项目 · Projects'],['tasks','tasks','任务 · Tasks'],['achievements','achievements','成果 · Evidence']]),university:()=>collectionPage('大学','University','课程、作业和学习证据。',[['courses','courses','课程 · Courses'],['tasks','tasks','作业 · Assessments'],['reviews','reviews','反思 · Reflection']]),study:()=>collectionPage('学习','Study','能力领域、英语与输出。',[['areas','study','领域 · Areas'],['english','english','英语 · English'],['reading','reading','阅读 · Reading']]),reading:()=>collectionPage('阅读','Reading','书、论文、电影和输出笔记。',[['reading','reading','阅读库 · Library'],['reviews','reviews','阅读复盘 · Review']]),health:()=>collectionPage('健康','Health','睡眠、运动、饮食、护肤和情绪记录。',[['health','health','健康记录 · Logs'],['sop','sop','健康 SOP']]),life:()=>collectionPage('生活','Life','SOP、库存、厨房、旅行和风格。',[['sop','sop','生活 SOP'],['inventory','inventory','库存 · Inventory'],['recipes','recipes','菜谱 · Recipes'],['journal','journal','日记 · Journal'],['travel','travel','旅行 · Travel'],['style','style','风格 · Style'],['money','money','金钱 · Money']]),review:()=>collectionPage('复盘','Review','把进展、阻碍与下一步连接起来。',[['reviews','reviews','复盘 · Reviews'],['achievements','achievements','成就 · Achievements']]),data:dataPage};(routes[route]||home)()}
  function bindDynamic(){document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openEditor(b.dataset.add));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const [key,id]=b.dataset.edit.split(':');openEditor(key,id)});document.querySelectorAll('[data-route-jump]').forEach(b=>b.onclick=()=>go(b.dataset.routeJump))}
  function openEditor(key,id=''){const spec=specs[key],old=rows(key).find(x=>x.id===id)||{};editing={key,id};$('editorTitle').textContent=spec.title;$('deleteButton').hidden=!id;$('editorFields').innerHTML=spec.fields.map(([name,label,type,options])=>`<div class="field ${type==='textarea'?'full':''}"><label for="field-${name}">${label}</label>${type==='select'?`<select id="field-${name}" name="${name}">${options.map(o=>`<option ${old[name]===o?'selected':''}>${esc(o)}</option>`).join('')}</select>`:type==='textarea'?`<textarea id="field-${name}" name="${name}">${esc(old[name]||'')}</textarea>`:`<input id="field-${name}" name="${name}" type="${type}" value="${esc(old[name]||(type==='date'?today():''))}">`}</div>`).join('');$('editor').showModal();setTimeout(()=>$('editorFields').querySelector('input,textarea,select')?.focus(),30)}
  function commitEditor(){const form=new FormData($('editorForm')),item={id:editing.id||uid()};for(const [k,v] of form)item[k]=String(v).trim();if(!item.title){toast('请填写标题 · Title required');return false}const data=rows(editing.key);state.collections[editing.key]=editing.id?data.map(x=>x.id===editing.id?item:x):[item,...data];save();render();return true}
  function deleteEditor(){if(!editing?.id||!confirm('删除这条记录？'))return;state.collections[editing.key]=rows(editing.key).filter(x=>x.id!==editing.id);save();$('editor').close();render()}
  function exportData(){const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`becoming-backup-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  const firstText=(x,keys)=>{for(const k of keys){const v=x?.[k];if(v!==undefined&&v!==null&&String(v).trim())return String(v)}return''};
  const legacyRow=(x={},fallback='记录')=>({id:String(x.id||uid()),title:firstText(x,['title','name','text','item','topic','book','place','projectTitle'])||fallback,status:firstText(x,['status','type','level','cadence','category'])||'record',date:firstText(x,['date','dueDate','deadline','createdAt','at']).slice(0,10),area:firstText(x,['area','context','term','author','location','cuisine','currency']),notes:firstText(x,['notes','note','summary','reflection','evidence','next','steps','ingredients','content','why','outcome','description'])});
  const addLegacy=(target,value,fallback)=>{if(Array.isArray(value))state.collections[target].push(...value.map(x=>legacyRow(x,fallback)));};
  function migrateLegacy(parsed){state=blank();addLegacy('tasks',parsed.tasks,'任务');addLegacy('projects',parsed.projects,'项目');addLegacy('courses',parsed.studyModules,'课程');addLegacy('study',parsed.studyAreas,'学习领域');addLegacy('reading',parsed.books,'阅读');addLegacy('reading',parsed.readingLogs,'阅读记录');addLegacy('english',parsed.english,'英语练习');addLegacy('health',parsed.foods,'饮食记录');addLegacy('health',parsed.weights,'体重记录');addLegacy('sop',parsed.routines,'SOP');addLegacy('inventory',parsed.inventory,'库存');addLegacy('recipes',parsed.recipes,'菜谱');addLegacy('journal',parsed.journal,'日记');addLegacy('travel',parsed.trips,'旅行');addLegacy('style',parsed.styleItems,'风格');addLegacy('money',parsed.moneyTransactions,'收支');addLegacy('money',parsed.moneyBudgets,'预算');addLegacy('money',parsed.wishlist,'愿望');addLegacy('achievements',parsed.customAchievements,'成就');addLegacy('achievements',parsed.pointsLog,'积分');addLegacy('reviews',parsed.decisionLog,'决策记录');
    if(parsed.reviewDaily?.entries&&typeof parsed.reviewDaily.entries==='object')for(const [date,x]of Object.entries(parsed.reviewDaily.entries))state.collections.reviews.push({...legacyRow(x,'每日复盘'),date});
    if(parsed.reflections&&typeof parsed.reflections==='object')for(const [date,x]of Object.entries(parsed.reflections))state.collections.reviews.push({...legacyRow(typeof x==='object'?x:{notes:x},'复盘'),date});
    if(parsed.care?.entries&&typeof parsed.care.entries==='object')for(const [date,x]of Object.entries(parsed.care.entries))state.collections.health.push({...legacyRow(x,'心灵关怀'),date,status:'mood'});
    if(parsed.habits?.definitions&&Array.isArray(parsed.habits.definitions))addLegacy('health',parsed.habits.definitions,'健康习惯');
    return Object.values(state.collections).reduce((n,a)=>n+a.length,0);
  }
  async function importData(file){try{const parsed=JSON.parse(await file.text());let count=0;if(parsed?.collections){state=parsed;for(const key of Object.keys(blank().collections))if(!Array.isArray(state.collections[key]))state.collections[key]=[];count=Object.values(state.collections).reduce((n,a)=>n+a.length,0)}else if(parsed&&typeof parsed==='object'){count=migrateLegacy(parsed)}else throw Error('invalid');save();render();toast(`已导入 ${count} 条记录 · Import complete`)}catch(error){console.error(error);toast('无法导入：请使用本站或旧工作台导出的 JSON')}}
  function search(){const q=$('searchInput').value.trim().toLowerCase(),all=[];for(const [key,data] of Object.entries(state.collections))for(const x of data)if(JSON.stringify(x).toLowerCase().includes(q))all.push({key,x});$('searchResults').innerHTML=q?(all.length?all.slice(0,50).map(({key,x})=>`<button class="search-result" data-search-edit="${key}:${x.id}"><strong>${esc(x.title)}</strong><small>${esc(specs[key]?.title||key)} · ${esc(x.notes||'')}</small></button>`).join(''):'<div class="empty">没有匹配记录。</div>'):'<div class="empty">输入关键词开始搜索。</div>';document.querySelectorAll('[data-search-edit]').forEach(b=>b.onclick=()=>{const [key,id]=b.dataset.searchEdit.split(':');$('searchDialog').close();openEditor(key,id)})}
  $('captureButton').onclick=()=>openEditor('tasks');$('searchButton').onclick=()=>{$('searchInput').value='';search();$('searchDialog').showModal();setTimeout(()=>$('searchInput').focus(),30)};$('searchInput').oninput=search;$('menuButton').onclick=()=>$('sidebar').classList.toggle('open');$('saveButton').onclick=e=>{e.preventDefault();if(commitEditor())$('editor').close()};$('deleteButton').onclick=deleteEditor;$('importInput').onchange=e=>{if(e.target.files[0])importData(e.target.files[0]);e.target.value=''};window.addEventListener('hashchange',()=>{route=location.hash.slice(1).split('/')[0]||'home';nav();render()});route=location.hash.slice(1).split('/')[0]||'home';nav();render();
})();
